apiVersion: apps/v1
kind: Deployment
metadata:
  name: fspiop-api-svc
  namespace: vnext
spec:
  template:
    spec:
      containers:
      - name: fspiop-api-svc
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "640Mi"
            cpu: "500m"