apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newphee-operator
rules:
  - apiGroups: ["paymenthub.mifos.io"]
    resources: ["newphees"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["paymenthub.mifos.io"]
    resources: ["newphees/status"]
    verbs: ["patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "namespaces", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
