apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newphee-operator
subjects:
  - kind: ServiceAccount
    name: newphee-operator
    namespace: newphee
roleRef:
  kind: ClusterRole
  name: newphee-operator
  apiGroup: rbac.authorization.k8s.io
