apiVersion: gazelle.mifos.io/v1
kind: PaymentHubDeployment
metadata:
  name: ph-ee-operations-web
  namespace: paymenthub
spec:
  enabled: true
  domain: GAZELLE_DOMAIN
  volMount:
    enabled: true
    name: ph-ee-operations-web-configmap
  replicas: 1
  image: docker.io/openmf/ph-ee-operations-web:dev
  containerPort: 80
  resources:
    limits:
      cpu: 500m
      memory: 512M
    requests:
      cpu: 100m
      memory: 256M
  rbacEnabled: false
  secretEnabled: false
  configMapEnabled: true
  ingressEnabled: true
  ingress:
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      - secretName: sandbox-secret
    rules:
      - host: ops.local
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: ph-ee-operations-web
                port:
                  number: 4200
  services:
    - name: ph-ee-operations-web
      ports:
        - name: port
          port: 4200
          targetPort: 80
          protocol: TCP
      selector:
        app: ph-ee-operations-web
      sessionAffinity: None
      type: ClusterIP
  livenessProbe:
    path: /
    port: 80
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    path: /
    port: 80
    initialDelaySeconds: 20
    periodSeconds: 30
    failureThreshold: 3
    timeoutSeconds: 5
  environment:
    - name: PH_OPS_BACKEND_SERVER_URL
      value: "https://ops-bk.GAZELLE_DOMAIN/api/v1"
    - name: PH_VOU_BACKEND_SERVER_URL
      value: "https://ops-bk.GAZELLE_DOMAIN/api/v1"
    - name: PH_ACT_BACKEND_SERVER_URL
      value: "https://identity-mapper.GAZELLE_DOMAIN"
    - name: PH_OPS_BULK_CONNECTOR_URL
      value: "https://connector-bulk.GAZELLE_DOMAIN"
    - name: PH_OPS_SIGNATURE_URL
      value: "https://ops-bk.GAZELLE_DOMAIN/api/v1/util/x-signature"
    - name: PH_PLATFORM_TENANT_ID
      value: "greenbank"
    - name: PH_PLATFORM_TENANT_IDS
      value: "greenbank,bluebank,redbank"
    - name: PH_REGISTERING_INSTITUTION_ID
      value: "123"
    - name: PH_DEFAULT_LANGUAGE
      value: "en"
    - name: PH_SUPPORTED_LANGUAGES
      value: "en,fr,es"
    - name: PH_AUTH_ENABLED
      value: "false"
    - name: PH_OAUTH_ENABLED
      value: "false"
    - name: PH_OAUTH_TYPE
      value: "keycloak"
    - name: PH_OAUTH_SERVER_URL
      value: "https://ops-bk.GAZELLE_DOMAIN/auth"
    - name: PH_OAUTH_REALM
      value: "paymenthub"
    - name: PH_OAUTH_CLIENT_ID
      value: "opsapp"
    - name: PH_OAUTH_CLIENT_SECRET
      value: "Y2xpZW50Og=="
    - name: PH_OAUTH_BASIC_AUTH
      value: "true"
    - name: PH_OAUTH_BASIC_AUTH_TOKEN
      value: "Y2xpZW50Og=="
