apiVersion: paymenthub.mifos.io/v1alpha1
kind: NewPhee
metadata:
  name: newphee-default
  namespace: newphee
spec:
  enabled: true
  replicas: 1
  namespace: newphee
  image:
    repository: newphee
    tag: latest
  zeebeGateway: zeebe-gateway.paymenthub.svc.cluster.local:26500
  paymenthub:
    namespace: paymenthub
    operationsDb:
      host: operationsmysql.paymenthub.svc.cluster.local
